version: "3.8"

services:

  db:
    container_name: dds_database
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DDS_MYSQL_ROOT_PASS}
      - MYSQL_USER=${DDS_MYSQL_USER}
      - MYSQL_PASSWORD=${DDS_MYSQL_PASS}
      - MYSQL_DATABASE=DeliverySystem
    restart: on-failure
    ports:
      - 127.0.0.1:3306:3306
    # Test to see if the database is accessible. Backend waits for this with 'condition: service_healthy'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: dds_backend
    image: dds-backend-local:latest
    build:
      dockerfile: Dockerfiles/backend.Dockerfile
      context: ./
    working_dir: /code
    command: bash -c "flask db upgrade && flask init-dev-db && flask run -h 0.0.0.0 -p 5000"
    environment:
      - DDS_APP_CONFIG=/code/dds_web/sensitive/dds_app.cfg
      - FLASK_ENV=development
      - FLASK_APP=dds_web
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    ports:
      - 127.0.0.1:5000:5000
    volumes:

      # Main website files (so can edit locally)
      - type: bind
        source: ./dds_web
        target: /code/dds_web

      # Sensitive config files: s3_config.json / .dds-cli.json / dds_app.cfg
      - type: bind
        source: $DDS_SENSITIVE_FILES
        target: /code/dds_web/sensitive

      # Migrations
      - type: bind
        source: ./migrations
        target: /code/migrations

      # Logging outputs
      - type: bind
        source: $DDS_LOG_DIR
        target: /dds_web/logs

      # Staged uploads
      - type: bind
        source: $DDS_UPLOAD_TEST
        target: /dds_web/uploads

      # Staged download
      - type: bind
        source: $DDS_DOWNLOAD_TEST
        target: /dds_web/downloads

      # Cache test (?)
      - type: bind
        source: $DDS_TEMP_CACHE_TEST
        target: /dds_web/local_temp_cache
