"""add_totp

Revision ID: da06dfa5759f
Revises: 19b877061c98
Create Date: 2022-04-11 08:45:14.397557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "da06dfa5759f"
down_revision = "19b877061c98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("totp_enabled", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("_totp_secret", sa.LargeBinary(length=64), nullable=True))
    op.add_column("users", sa.Column("totp_last_verified", sa.DateTime(), nullable=True))

    # Fill in default value for totp_enabled
    user_table = sa.sql.table(
        "users",
        sa.sql.column("totp_enabled", mysql.TINYINT(display_width=1)),
    )
    op.execute(user_table.update().values(totp_enabled=False))

    # Make totp_enabled not nullable
    op.alter_column(
        "users", "totp_enabled", existing_type=mysql.TINYINT(display_width=1), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_last_verified")
    op.drop_column("users", "_totp_secret")
    op.drop_column("users", "totp_enabled")
    # ### end Alembic commands ###
